version: "3.9"
services:
    nginx:
        build:
            context: docker
            dockerfile: dev/nginx/Dockerfile
        volumes:
            - ./app/public:/app/public
        depends_on:
            - php-fpm
    php-fpm:
        build:
            context: docker
            dockerfile: dev/php-fpm/Dockerfile
        volumes:
            - ./app:/app
            - ./docker/dev/php-fpm/xdebug-fpm.ini:/usr/local/etc/php/conf.d/xdebug-fpm.ini
    php-cli:
        build:
            context: docker
            dockerfile: dev/php-cli/Dockerfile
        volumes:
            - ./app:/app
            - ./docker/dev/php-cli/xdebug-cli.ini:/usr/local/etc/php/conf.d/xdebug-cli.ini
    db:
        image: postgres:13-alpine
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
        volumes:
            - ./docker/common/postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
            - db:/var/lib/postgresql/data
    adminer:
        build:
            context: docker
            dockerfile: dev/adminer/Dockerfile
        depends_on:
            - db
        environment:
            ADMINER_DEFAULT_SERVER: db
            ADMINER_PLUGINS: "dump-date dump-zip enum-option enum-types"

volumes:
    db:
