services:
    nginx:
        ports:
            - "888:80"
    db:
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            #POSTGRES_DB: postgres
        ports:
            - "6753:5432"
    adminer:
        ports:
            - "8811:8080"
