version: "3.9"
services:
    nginx:
        image: ${REGISTRY}/${COMPOSE_PROJECT_NAME}:nginx-${IMAGE_VERSION}
        restart: always
        ports:
            - "80:80"
        depends_on:
            - php-fpm
    php-fpm:
        image: ${REGISTRY}/${COMPOSE_PROJECT_NAME}:php-fpm-${IMAGE_VERSION}
        restart: always
    php-cli:
        image: ${REGISTRY}/${COMPOSE_PROJECT_NAME}:php-cli-${IMAGE_VERSION}
    db:
        image: postgres:13-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - db:/var/lib/postgresql/data

volumes:
    db:
