FROM php:8.1-cli-alpine

# system update need for production only
# RUN apk update && apk upgrade --no-cache

# unzip need by composer
RUN apk add --no-cache unzip

# PHP intl extension
RUN apk add --no-cache icu-dev && \
    docker-php-ext-install intl && \
    docker-php-ext-configure intl

# PHP PostgreSQL extension
RUN apk --no-cache add postgresql-dev && \
    docker-php-ext-install pdo_pgsql

# xdebug
RUN apk --no-cache --virtual build-deps add \
    autoconf g++ make && \
    pecl install xdebug && \
    docker-php-ext-enable xdebug && \
    apk del -f build-deps

# delete garbage
RUN apk del gcc g++ && \
    rm -rf /tmp/pear

# PHP_INI_DIR is set inside php image
RUN mv $PHP_INI_DIR/php.ini-development $PHP_INI_DIR/php.ini

COPY ./common/php/conf.d $PHP_INI_DIR/conf.d

ENV COMPOSER_ALLOW_SUPERUSER 1
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/bin --filename=composer --quiet

WORKDIR /app
